# Generated by Django 3.2.3 on 2022-08-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsetting',
            name='cur_year',
            field=models.IntegerField(default=1400),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='end_time',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='lim_md',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='lim_mm',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='lim_my',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='start_time',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
