# Generated by Django 3.2.3 on 2022-08-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20220821_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruser',
            name='isadmin',
        ),
        migrations.RemoveField(
            model_name='ruser',
            name='ismali',
        ),
        migrations.RemoveField(
            model_name='ruser',
            name='issigner',
        ),
    ]
