# Generated by Django 3.2.3 on 2022-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220821_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsetting',
            name='amoozesh',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='baygan',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='dasttaghsim',
            field=models.IntegerField(default=7.33),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='dastzarb',
            field=models.IntegerField(default=1.4),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='hozoor',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='kharidm',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='mablagh1',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='mablagh2',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='mali',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='mamooriat',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='nagah_ezaf',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='negah1',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='negah2',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='negah3',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='ranande',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='rel_work',
            field=models.IntegerField(default=6.5),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='signer',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='rsetting',
            name='work_time',
            field=models.IntegerField(default=7),
        ),
    ]
