# Generated by Django 3.2.3 on 2022-08-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20220822_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsetting',
            name='cur_year',
            field=models.IntegerField(default=1400, verbose_name='سال جاری'),
        ),
    ]
