# Generated by Django 3.2.3 on 2022-08-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_rsetting_cur_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsetting',
            old_name='start_time',
            new_name='StartTime',
        ),
    ]
