# Generated by Django 3.2.3 on 2022-08-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_start_time_rsetting_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsetting',
            name='StartTime',
        ),
        migrations.RemoveField(
            model_name='rsetting',
            name='title',
        ),
        migrations.AddField(
            model_name='rsetting',
            name='start_time',
            field=models.IntegerField(default=7, verbose_name='ساعت شروع فعالیت سازمان'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='amoozesh',
            field=models.IntegerField(default=10001, verbose_name='شماره پرسنلی مسئول آموزش'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='baygan',
            field=models.IntegerField(default=10001, verbose_name='شماره پرسنلی مسئول بایگانی'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='dasttaghsim',
            field=models.IntegerField(default=7.33, verbose_name='تقسيم بر '),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='dastzarb',
            field=models.IntegerField(default=1.4, verbose_name=' دستمزد ماهيانه ضربدر'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='end_time',
            field=models.IntegerField(default=14, verbose_name='ساعت پایان فعالیت سازمان'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='hozoor',
            field=models.IntegerField(default=10001, verbose_name='شماره پرسنلی مسئول حضور و غیاب'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='kharidm',
            field=models.IntegerField(default=2, verbose_name='تعداد روز مرخصي قابل خريد'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='lim_md',
            field=models.IntegerField(default=2, verbose_name='محدودیت مرخصی در روز(به ساعت)'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='lim_mm',
            field=models.IntegerField(default=15, verbose_name='محدودیت مرخصی در ماه(به روز)'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='lim_my',
            field=models.IntegerField(default=31, verbose_name='محدودیت مرخصی در سال(به روز)'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='mablagh1',
            field=models.IntegerField(default=10000000, verbose_name='مبلغ هر روز ماموریت راننده به ریال'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='mablagh2',
            field=models.IntegerField(default=10000000, verbose_name='مبلغ ثابت براي راننده اول و دوم به ریال'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='mali',
            field=models.IntegerField(default=10001, verbose_name='شماره پرسنلی مدیر امور مالی'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='mamooriat',
            field=models.IntegerField(default=10000000, verbose_name='مبلغ هر روز ماموریت به ریال'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='nagah_ezaf',
            field=models.IntegerField(default=2, verbose_name='تعداد روزهای اضافه کار ثابت نگهبانان'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='negah1',
            field=models.IntegerField(default=10001, verbose_name='شماره پرسنلی نگهبان 1'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='negah2',
            field=models.IntegerField(default=10001, verbose_name='شماره پرسنلی نگهبان 1'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='negah3',
            field=models.IntegerField(default=10001, verbose_name='شماره پرسنلی نگهبان 1'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='ranande',
            field=models.IntegerField(default=10001, verbose_name='شماره پرسنلی راننده'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='rel_work',
            field=models.IntegerField(default=6.5, verbose_name='نسبت روز کاری به مرخصی ساعتی'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='signer',
            field=models.IntegerField(default=10001, verbose_name='امضاء کننده'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='work_time',
            field=models.IntegerField(default=7, verbose_name='ساعت کاری در روز'),
        ),
    ]
