# Generated by Django 3.2.3 on 2022-08-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20220822_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsetting',
            name='dasttaghsim',
            field=models.FloatField(default=7.33, verbose_name='تقسيم بر '),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='dastzarb',
            field=models.FloatField(default=1.4, verbose_name=' دستمزد ماهيانه ضربدر'),
        ),
        migrations.AlterField(
            model_name='rsetting',
            name='rel_work',
            field=models.FloatField(default=6.5, verbose_name='نسبت روز کاری به مرخصی ساعتی'),
        ),
    ]
