# Generated by Django 3.2.3 on 2022-08-28 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20220823_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.CharField(max_length=10)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=10)),
                ('sick_paper', models.ImageField(upload_to='images')),
                ('signer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterModelOptions(
            name='ruser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='pass',
            name='pass_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.passtype'),
        ),
        migrations.AddField(
            model_name='pass',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.statetype'),
        ),
        migrations.AddField(
            model_name='pass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
