# Generated by Django 3.2.3 on 2022-09-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220828_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menumodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=30, null=True)),
                ('classs', models.CharField(max_length=30, null=True)),
                ('parent', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pass',
            name='state',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app1.statetype'),
        ),
    ]
