# Generated by Django 3.2.3 on 2022-09-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20220906_0904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menumodel',
        ),
    ]
