# Generated by Django 3.2.3 on 2022-09-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_delete_menumodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='sick_paper',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
