# Generated by Django 3.2.3 on 2022-09-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_pass_sick_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='sick_paper',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='signer',
            field=models.CharField(default='10001', max_length=10),
        ),
    ]
