# Generated by Django 3.2.3 on 2022-09-08 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20220907_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='end_date',
            field=models.CharField(max_length=10, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='end_time',
            field=models.CharField(max_length=10, verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='pass_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.passtype', verbose_name='نوع مرخصی '),
        ),
        migrations.AlterField(
            model_name='pass',
            name='reason',
            field=models.CharField(max_length=10, verbose_name='علت درخواست'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='req_date',
            field=models.CharField(max_length=10, verbose_name='تاریخ  ثبت درخواست'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='sick_paper',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='گواهی درخواست'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='signer',
            field=models.CharField(default='10001', max_length=10, verbose_name='تایید کننده'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='start_date',
            field=models.CharField(max_length=10, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='start_time',
            field=models.CharField(max_length=10, verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='state',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app1.statetype', verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
    ]
